# Page settings

baseurl = "http://lisancao.github.io"
languageCode = "en-us"
title = "Lisa N. Cao CV"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = false
disableSitemap = false
disable404 = false

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-3.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Lisa N. Cao"
        tagline = "Undergraduate Student, R & Linux Enthusiast"
        avatar = "lisancao.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: lisanatashacao@gmail.com"
        title = "lisanatashacao@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+17789994798"
        title = "+17789994798"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "lisancao.github.io"
        title = "lisancao.github.io"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/lisancao"
        title = "linkedin.com/in/lisancao"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/lisancao"
        title = "github.com/lisancao"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/lisancao"
        title = "@lisancao"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "B.A. in Psychology"
        college = "Simon Fraser University"
        dates = "2012 - Present"

        [[params.education.list]]
        degree = "Dogwood Diploma, IB Certificate"
        college = "Britannia Secondary School"
        dates = "2007 - 2012"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Advanced"

        [[params.language.list]]
        language = "Vietnamese"
        level = "Beginner"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"
        
        [[params.interests.list]]
        interest = "Vancouver Datajam"
        
        [[params.interests.list]]
        interest = "SFU Scientific Programming"
        
        [[params.interests.list]]
        interest = "RLadies Vancouver"
        
        [[params.interests.list]]
        interest = "PyLadies Vancouver"

        [[params.interests.list]]
        interest = "Canadian Association of Neuroscience"


# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "I use R, Bash, and Python to build open source tools for bioinformaticians and behavioural neuroscientists. My community work includes organizing for RLadies Vancouver and sitting as the current Chair for the Vancouver Datajam, as well as running workshops with the SFU Scientific Programming Group."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Workshop Facilitator"
        dates = "2018 - Present"
        company = "SFU Scientific Programming Group "
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

        [[params.jobs.list]]
        position = "Research Assistant"
        dates = "2016 - Present"
        company = "Sleep and Circadian Neuroscience Lab, Dr. Ralph Mistlberger"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

        [[params.jobs.list]]
        position = "Research Assistant"
        dates = "2015 - Present"
        company = "Behavioural Endocrinology Lab, Dr. Neil V. Watson"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

        [[params.jobs.list]]
        position = "Co-Investigator"
        dates = "2016"
        company = "Vancouver Women’s Health Collective"
        details = "Community funded research for work investigating resource allocation for at-risk women in Downtown Eastside Vancouver. *Principal investigator: France-Emanuelle Jolie*"


    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "BiocSwirl"
        url = "https://github.com/biocswirl-dev-team/BiocSwirl"
        tagline = "In-depth SwirlStats style courses used to teach bioinformatics workflows in R using an interactive and easy to digest format."

        [[params.projects.list]]
        title = "BiocTerm"
        url = "https://github.com/biocswirl-dev-team/BiocTerm"
        tagline = "A highly configurable, lightweight and feature rich terminal interface with multi-language support for conducting bioinformatics."
        
        [[params.projects.list]]
        title = "behavendoR"
        url = "https://github.com/lisancao/behavendoR"
        tagline = "R package used to introduce statistical workflows and reproducibility into the Behavioural Endocrinology field."


    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Technical, Laboratory, & Organizational Skills"

        [[params.skills.list]]
        skill = "R"
        level = "80%"
                
        [[params.skills.list]]
        skill = "Bash"
        level = "75%"

        [[params.skills.list]]
        skill = "Python"
        level = "65%"

        [[params.skills.list]]
        skill = "Team-Leading"
        level = "90%"              
        
        [[params.skills.list]]
        skill = "Project Management"
        level = "85%"      
        
        
        [[params.skills.list]]
        skill = "Wet Lab Skills (Neuroscience methods)"
        level = "65%"
        


    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
